'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Info As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''ASPxFormLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout
    
    '''<summary>
    '''LayoutItemNestedControlContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer1 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''firstNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstNameTextBox As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer2 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''lastNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lastNameTextBox As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer3 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''genderRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents genderRadioButtonList As Global.DevExpress.Web.ASPxRadioButtonList
    
    '''<summary>
    '''LayoutItemNestedControlContainer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer4 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''birthDateEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents birthDateEdit As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''LayoutItemNestedControlContainer7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer7 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''phoneNumberTestBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phoneNumberTestBox As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''LayoutItemNestedControlContainer5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LayoutItemNestedControlContainer5 As Global.DevExpress.Web.LayoutItemNestedControlContainer
    
    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''submitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitButton As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''cancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cancelButton As Global.DevExpress.Web.ASPxButton
End Class
